title:            Restless Point
tagline:          info for restless people
description:      "Restless point."
logo:             logo-50.png
disqus_shortname: restlesspoint
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://restlesspoint.com

# Owner/author information
owner:
  name:           Restlesss Point Authors
  avatar:         taras-kalapun-photo.jpg
  bio:            
  email:          t@kalapun.com
  twitter:        
  instagram:      
  github:         
  facebook:       
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "http://plus.google.com/+TarasKalapun"

feed: http://feeds.feedburner.com/RestlessPoint

google_analytics: UA-2087894-20
google_verify: 
bing_verify:   
alexa_verify:  

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
# http://jekyllrb.com/docs/permalinks/

permalink:   /:categories/:title/
relative_permalinks: false

# Internal pages/posts to include in top navigation
links:
  - title: Travel
    url: /travel/
  - title: Spots
    url: /spots/
  - title: Articles
    url: /articles/
  - title: Map
    url: /map/
  - title: About
    url: /about/

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["vendor",".bundle","lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json"]

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: "http://restlesspoint.com"
  relativeLinks: 'http://restlesspoint.com/api/links.jsonp'
  media: 'images'
  # site:
  #     tags: "https://www.healthcare.gov/api/tags.jsonp"
  ignore:
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          label: "Layout type"
          options: 
            - name: "post"
              value: "post"
            - name: "page"
              value: "page"
          selected: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options: "http://restlesspoint.com/api/tags.jsonp"
          alterable: true
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
    _posts/travel:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "travel"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options: "http://restlesspoint.com/api/tags.jsonp"
          alterable: true
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
    _posts/spots:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "spots"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options: "http://restlesspoint.com/api/tags.jsonp"
          alterable: true
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
    _posts/articles:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "hidden"
          value: "articles"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options: "http://restlesspoint.com/api/tags.jsonp"
          alterable: true
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true

